# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from dbw_demo/control.msg. Do not edit."""
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct


class control(genpy.Message):
  _md5sum = "9198f2552165ab2d06332d076b42111d"
  _type = "dbw_demo/control"
  _has_header = False #flag to mark the presence of a Header object
  _full_text = """
  float32 brake
  float32 throttle
  float32 steering
  bool steering_mult
  int16 gear_cmd
  int16 turn_signal_cmd
"""
  __slots__ = ['brake','throttle','steering','steering_mult','gear_cmd','turn_signal_cmd']
  _slot_types = ['float32','float32','float32','bool','int16','int16']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       brake,throttle,steering,steering_mult,gear_cmd,turn_signal_cmd

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(control, self).__init__(*args, **kwds)
      #message fields cannot be None, assign default values for those that are
      if self.brake is None:
        self.brake = 0.
      if self.throttle is None:
        self.throttle = 0.
      if self.steering is None:
        self.steering = 0.
      if self.steering_mult is None:
        self.steering_mult = False
      if self.gear_cmd is None:
        self.gear_cmd = 0
      if self.turn_signal_cmd is None:
        self.turn_signal_cmd = 0
    else:
      self.brake = 0.
      self.throttle = 0.
      self.steering = 0.
      self.steering_mult = False
      self.gear_cmd = 0
      self.turn_signal_cmd = 0

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_get_struct_3fB2h().pack(_x.brake, _x.throttle, _x.steering, _x.steering_mult, _x.gear_cmd, _x.turn_signal_cmd))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    try:
      end = 0
      _x = self
      start = end
      end += 17
      (_x.brake, _x.throttle, _x.steering, _x.steering_mult, _x.gear_cmd, _x.turn_signal_cmd,) = _get_struct_3fB2h().unpack(str[start:end])
      self.steering_mult = bool(self.steering_mult)
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_get_struct_3fB2h().pack(_x.brake, _x.throttle, _x.steering, _x.steering_mult, _x.gear_cmd, _x.turn_signal_cmd))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    try:
      end = 0
      _x = self
      start = end
      end += 17
      (_x.brake, _x.throttle, _x.steering, _x.steering_mult, _x.gear_cmd, _x.turn_signal_cmd,) = _get_struct_3fB2h().unpack(str[start:end])
      self.steering_mult = bool(self.steering_mult)
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_3fB2h = None
def _get_struct_3fB2h():
    global _struct_3fB2h
    if _struct_3fB2h is None:
        _struct_3fB2h = struct.Struct("<3fB2h")
    return _struct_3fB2h
